### ISSUE TITLE
Disabling line numbers

### ISSUE THREAD

**Issue by injust** [catppuccin/delta#12]
Catppuccin sets `line-numbers = true` in delta by default. This is non-trivial to disable, as there is no flag like `--no-line-numbers` (at least until https://github.com/clap-rs/clap/issues/815).

After reading https://github.com/dandavison/delta/issues/307, the best way I found[^1] was to add a delta "feature" to your gitconfig[^2]:

```gitconfig
[delta "no-line-numbers"]
	line-numbers = false
```

Then either export `DELTA_FEATURES=+no-line-numbers`, or prefix it to your delta and git commands.

Since Catppuccin's theme is a delta "feature" itself, using another "feature" to override it is a bit of an edge case. I think we should either:

1. Document this in the README, or
2. Stop enabling line numbers by default.

[^1]: Another way is to run git with `git -c delta.line-numbers=false`, but that only works when running delta via git.

[^2]: https://github.com/dandavison/delta/issues/446 doesn't apply in this case, maybe because Catppuccin sets `line-numbers = true` in a "feature".

**Comment by Anomalocaridid** [comment]
I opted to stop enabling line numbers by default. This seems much simpler for users to change themselves and the theme should minimize assumptions about user preferences anyways.

**Comment by injust** [comment]
This is weird: When you pass `--line-numbers` to delta, it gives you non-Catppuccin line numbers.

https://github.com/dandavison/delta/issues/1837
