### ISSUE TITLE
Now Catppuccin themes for `bat` use space

### ISSUE THREAD

**Issue by mvisat** [catppuccin/delta#4]
instead of hyphen, e.g. `Catppuccin Mocha` https://github.com/catppuccin/bat?tab=readme-ov-file#configuration-file

These coule be modified:
https://github.com/catppuccin/delta/blob/21b37ac3138268d92cee71dfc8539d134817580a/template.gitconfig#L26
https://github.com/catppuccin/delta/blob/21b37ac3138268d92cee71dfc8539d134817580a/themes/mocha.gitconfig#L26

and other flavors.

**Comment by Anomalocaridid** [comment]
Fixed with https://github.com/catppuccin/delta/commit/765eb17d0268bf07c20ca439771153f8bc79444f
