### ISSUE TITLE
Should specify in README, that installing `catppuccin/bat` is a pre-requisite

### ISSUE THREAD

**Issue by shiroyasha9** [catppuccin/delta#5]
I was getting the below error every time I ran `delta`, and the theme was not being applied. 

`[bat warning]: Unknown theme 'Catppuccin Mocha', using default.`

It took me quite some time to understand that I need to explicitly install and setup `catppuccin/bat` for this to work. This should be added to README.md by default for people who are new to this (like me). 

I can add it if you think this is a good idea. 

Thanks!

**Comment by Anomalocaridid** [comment]
Sorry about that. It completely slipped my mind when I made this port.

By all means, go ahead and add it.
